name: On Push
#for every push on any branch
on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - name: Check branch name format
      id: check_branch
      run: |
        if [[ "${GITHUB_REF_NAME}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-dev$ ]]; then
          echo "match=true" >> $GITHUB_OUTPUT
        else
          echo "match=false" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v4
      if: steps.check_branch.outputs.match == 'true'
      with:
        fetch-depth: 0 # Fetch all history for all tags

    - name: install make
      if: steps.check_branch.outputs.match == 'true'
      run: sudo apt-get install -y make

    - name: setup Python ${{ matrix.python-version }}
      if: steps.check_branch.outputs.match == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      if: steps.check_branch.outputs.match == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage build

    - name: build
      if: steps.check_branch.outputs.match == 'true'
      run: make tests VERSION=${{ github.ref_name }}

    - name: publish test report
      if: steps.check_branch.outputs.match == 'true' && (success() || failure())
      uses: mikepenz/action-junit-report@v5
      with:
        report_paths: 'test-report.xml'
        include_passed: true

    - name: cobertura-report
      if: steps.check_branch.outputs.match == 'true' && success() || failure()
      uses: 5monkeys/cobertura-action@v14
      with:
        path: coverage.xml
        minimum_coverage: 80
        fail_below_threshold: true
        report_name: Coverage Report (${{ matrix.python-version }})