name: On Release
on:
  release:
    types: [published]


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all tags

    - name: install make
      run: sudo apt-get install -y make

    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: build
      run: make tests VERSION=${{ github.event.release.tag_name }}

    - name: publish test report
      if: success() || failure()
      uses: mikepenz/action-junit-report@v5
      with:
        report_paths: 'test-report.xml'
        include_passed: true


  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install make
      run: sudo apt-get install -y make

    - name: setup Python3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: build
      run : make VERSION=${{ github.event.release.tag_name }}

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/*

    - name: Publish release assets
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "dist/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  publish-pypi:
    name: Publish to PyPI
    needs: build-python
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gamuLogger
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

